name: firn
description: A modern IRC v3 library written for dart. Used in Igloo IRC for android.
version: 0.0.3
homepage: https://github.com/nojusr/firn

environment:
  sdk: '>=3.2.3 <4.0.0'


dev_dependencies:
  test: ^1.14.5
